[project]
name = "euclid_msi"
version = "0.0.1"
description = "A package for spatial lipidomics data analysis including preprocessing, embedding, clustering, postprocessing, case-control analysis, and plotting."
authors = [
  { name = "Luca Fusar Bassini", email = "luca.fusarbassini@epfl.ch" },
]
readme = "README.md"
requires-python = ">=3.8"
license = { text = "BSD 3-Clause" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = []

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
